dist: trusty
sudo: false
language: node_js
node_js:
- node
cache:
  directories:
  - node_modules


-: &npm_deploy
    provider: npm
    email: goncalo05@gmail.com
    api_key: $NPM_TOKEN
    skip_cleanup: true

deploy:
  - <<: *npm_deploy
    on:
      tags: true
      repo: ConsenSys/surya
      branch: master
  - <<: *npm_deploy
    on:
      repo: ConsenSys/surya
      branch: develop
      tag: next
